// ─── LEVEL DATA (revised) ──────────────────────────────────────────────────
//
// Changes from previous version:
//   • All words now have a `ja` field (Japanese translation)
//   • ja format: kana-only for levels 1-3, kanji+reading for 4-6, kanji-forward for 7-9
//   • Minimal pairs are marked with a comment // ⇔ pair
//   • Level 6 expanded to 18 words (medial TS added)
//   • Level 7 expanded to 18 words
//   • Several weak words replaced (see comments)
//
// Audio file naming convention (unchanged):
//   audio/{folder}/{sound}_{position}_{word}_{gender}.mp3
//
// NEW words requiring audio recording are marked: // 🎙 NEW
//
// ──────────────────────────────────────────────────────────────────────────

const levels = {

    // ── LEVEL 1 ── S vs SH ─────────────────────────────────────────────────
    1: { name:"S vs SH", folder:"S_vs_SH", sounds:["S","SH"], targets:["🌸","🦆","👾"],
         words:[
            {sound:"S", position:"initial", word:"sea",     ja:"うみ"},
            {sound:"S", position:"initial", word:"sail",    ja:"セール"},
            {sound:"S", position:"initial", word:"song",    ja:"うた"},
            {sound:"SH",position:"initial", word:"she",     ja:"かのじょ"},
            {sound:"SH",position:"initial", word:"shake",   ja:"ふる"},
            {sound:"SH",position:"initial", word:"show",    ja:"みせる"},
            {sound:"S", position:"medial",  word:"muscle",  ja:"きんにく"},
            {sound:"S", position:"medial",  word:"pencil",  ja:"えんぴつ"},
            {sound:"S", position:"medial",  word:"basin",   ja:"たらい"},
            {sound:"SH",position:"medial",  word:"nation",  ja:"くに"},
            {sound:"SH",position:"medial",  word:"fashion", ja:"ファッション"},
            {sound:"SH",position:"medial",  word:"ocean",   ja:"たいかい"},
            {sound:"S", position:"final",   word:"bus",     ja:"バス"},
            {sound:"S", position:"final",   word:"face",    ja:"かお"},
            {sound:"S", position:"final",   word:"nice",    ja:"すてき"},
            {sound:"SH",position:"final",   word:"bush",    ja:"しげみ"},
            {sound:"SH",position:"final",   word:"fish",    ja:"さかな"},
            {sound:"SH",position:"final",   word:"rush",    ja:"いそぐ"},
         ],
         stickers:[{emoji:"🌙",price:50},{emoji:"⭐",price:100},{emoji:"🌟",price:200},{emoji:"🌠",price:300},{emoji:"🌌",price:500}]},

    // ── LEVEL 2 ── S vs TH (voiceless) ────────────────────────────────────
    2: { name:"S vs TH", folder:"S_vs_TH_voiceless", sounds:["S","TH"], targets:["🦆","🪆","👾"],
         words:[
            {sound:"S", position:"initial", word:"sea",    ja:"うみ"},
            {sound:"S", position:"initial", word:"sir",    ja:"〜さん（男性）"},
            {sound:"S", position:"initial", word:"soap",   ja:"せっけん"},
            {sound:"TH",position:"initial", word:"thin",   ja:"うすい"},
            {sound:"TH",position:"initial", word:"think",  ja:"かんがえる"},
            {sound:"TH",position:"initial", word:"three",  ja:"さん"},
            {sound:"S", position:"medial",  word:"fossil", ja:"かせき"},
            {sound:"S", position:"medial",  word:"basin",  ja:"たらい"},
            {sound:"S", position:"medial",  word:"lesson", ja:"じゅぎょう"},
            {sound:"TH",position:"medial",  word:"author", ja:"ちょしゃ"},
            {sound:"TH",position:"medial",  word:"nothing",ja:"なにもない"},
            {sound:"TH",position:"medial",  word:"method", ja:"やりかた"},
            {sound:"S", position:"final",   word:"class",  ja:"クラス"},
            {sound:"S", position:"final",   word:"peace",  ja:"へいわ"},
            {sound:"S", position:"final",   word:"bus",    ja:"バス"},
            {sound:"TH",position:"final",   word:"bath",   ja:"おふろ"},
            {sound:"TH",position:"final",   word:"math",   ja:"すうがく"},
            {sound:"TH",position:"final",   word:"teeth",  ja:"は"},
         ],
         stickers:[{emoji:"🌬️",price:50},{emoji:"🍃",price:100},{emoji:"🌀",price:200},{emoji:"⚡",price:300},{emoji:"🌊",price:500}]},

    // ── LEVEL 3 ── F vs P ──────────────────────────────────────────────────
    3: { name:"F vs P", folder:"F_vs_P", sounds:["F","P"], targets:["🗼","🦆","🪆"],
         words:[
            {sound:"F", position:"initial", word:"fan",    ja:"せんぷうき"},
            {sound:"F", position:"initial", word:"feel",   ja:"かんじる"},
            {sound:"F", position:"initial", word:"photo",  ja:"しゃしん"},
            {sound:"P", position:"initial", word:"pan",    ja:"フライパン"},
            {sound:"P", position:"initial", word:"peel",   ja:"むく"},
            {sound:"P", position:"initial", word:"pot",    ja:"なべ"},
            {sound:"F", position:"medial",  word:"after",  ja:"あとで"},
            {sound:"F", position:"medial",  word:"offer",  ja:"もうしでる"},
            {sound:"F", position:"medial",  word:"sofa",   ja:"ソファ"},
            {sound:"F", position:"medial",  word:"effort", ja:"どりょく"},
            {sound:"P", position:"medial",  word:"paper",  ja:"かみ"},
            {sound:"P", position:"medial",  word:"open",   ja:"あける"},
            {sound:"P", position:"medial",  word:"topic",  ja:"わだい"},
            {sound:"F", position:"final",   word:"leaf",   ja:"は（葉）"},
            {sound:"F", position:"final",   word:"roof",   ja:"やね"},
            {sound:"F", position:"final",   word:"safe",   ja:"あんぜん"},
            {sound:"P", position:"final",   word:"leap",   ja:"とびはねる"},
            {sound:"P", position:"final",   word:"rope",   ja:"ロープ"},
            {sound:"P", position:"final",   word:"tape",   ja:"テープ"},
         ],
         stickers:[{emoji:"🍂",price:50},{emoji:"🦊",price:100},{emoji:"🍁",price:200},{emoji:"🦋",price:300},{emoji:"🌸",price:500}]},

    // ── LEVEL 4 ── L vs R ──────────────────────────────────────────────────
    4: { name:"L vs R", folder:"L_vs_R", sounds:["L","R"], targets:["🍥","🦆","🪆"],
         words:[
            {sound:"L", position:"initial", word:"lake",   ja:"湖（みずうみ）"},
            {sound:"L", position:"initial", word:"lane",   ja:"車線（しゃせん）"},
            {sound:"L", position:"initial", word:"low",    ja:"低い（ひくい）"},
            {sound:"L", position:"initial", word:"lock",   ja:"鍵（かぎ）"},
            {sound:"R", position:"initial", word:"rain",   ja:"雨（あめ）"},
            {sound:"R", position:"initial", word:"rake",   ja:"熊手（くまで）"},
            {sound:"R", position:"initial", word:"rice",   ja:"ご飯（ごはん）"},
            {sound:"R", position:"initial", word:"rock",   ja:"岩（いわ）"},
            {sound:"L", position:"medial",  word:"alive",  ja:"生きている（いきている）"},
            {sound:"L", position:"medial",  word:"balloon",ja:"風船（ふうせん）"},
            {sound:"L", position:"medial",  word:"below",  ja:"下（した）"},
            {sound:"L", position:"medial",  word:"collect",ja:"集める（あつめる）"},
            {sound:"R", position:"medial",  word:"carrot", ja:"にんじん"},
            {sound:"R", position:"medial",  word:"correct",ja:"正しい（ただしい）"},
            {sound:"R", position:"medial",  word:"mirror", ja:"鏡（かがみ）"},
            {sound:"R", position:"medial",  word:"river",  ja:"川（かわ）"},
            {sound:"L", position:"final",   word:"bell",   ja:"ベル"},
            {sound:"L", position:"final",   word:"hill",   ja:"丘（おか）"},
            {sound:"L", position:"final",   word:"tall",   ja:"背が高い（せがたかい）"},
            {sound:"R", position:"final",   word:"star",   ja:"星（ほし）"},
            {sound:"R", position:"final",   word:"door",   ja:"ドア"},
            {sound:"R", position:"final",   word:"far",    ja:"遠い（とおい）"},
         ],
         stickers:[{emoji:"☁️",price:50},{emoji:"🌱",price:100},{emoji:"🌲",price:200},{emoji:"🦅",price:300},{emoji:"💎",price:500}]},

    // ── LEVEL 5 ── Z vs TH (voiced) ────────────────────────────────────────
    5: { name:"Z vs TH (voiced)", folder:"Z_vs_TH_voiced", sounds:["Z","TH"], targets:["🐍","🦎","👾"],
         words:[
            {sound:"Z", position:"initial", word:"zoo",     ja:"動物園（どうぶつえん）"},
            {sound:"Z", position:"initial", word:"zone",    ja:"地域（ちいき）"},
            {sound:"Z", position:"initial", word:"zero",    ja:"ゼロ"},
            {sound:"TH",position:"initial", word:"they",    ja:"彼ら（かれら）"},
            {sound:"TH",position:"initial", word:"this",    ja:"これ"},
            {sound:"TH",position:"initial", word:"those",   ja:"あれら"},
            {sound:"Z", position:"medial",  word:"frozen",  ja:"凍った（こおった）"},
            {sound:"Z", position:"medial",  word:"razor",   ja:"かみそり"},
            {sound:"Z", position:"medial",  word:"season",  ja:"季節（きせつ）"},
            {sound:"TH",position:"medial",  word:"father",  ja:"父（ちち）"},
            {sound:"TH",position:"medial",  word:"mother",  ja:"母（はは）"},
            {sound:"TH",position:"medial",  word:"other",   ja:"他の（ほかの）"},
            {sound:"Z", position:"final",   word:"bees",    ja:"みつばち"},
            {sound:"Z", position:"final",   word:"nose",    ja:"鼻（はな）"},
            {sound:"Z", position:"final",   word:"phase",   ja:"段階（だんかい）"},
            {sound:"TH",position:"final",   word:"bathe",   ja:"入浴する（にゅうよくする）"},
            {sound:"TH",position:"final",   word:"breathe", ja:"呼吸する（こきゅうする）"},
            {sound:"TH",position:"final",   word:"soothe",  ja:"なだめる"},
         ],
         stickers:[{emoji:"🐝",price:50},{emoji:"🦎",price:100},{emoji:"🐍",price:200},{emoji:"🦁",price:300},{emoji:"🔥",price:500}]},

    // ── LEVEL 6 ── CH vs TS ────────────────────────────────────────────────
    6: { name:"CH vs TS", folder:"CH_vs_TS", sounds:["CH","TS"], targets:["⛩️","🏮","🎋"],
         words:[
            {sound:"CH", position:"initial", word:"chain",   ja:"鎖（くさり）"},
            {sound:"CH", position:"initial", word:"chip",    ja:"かけら"},
            {sound:"CH", position:"initial", word:"choose",  ja:"選ぶ（えらぶ）"},
            {sound:"CH", position:"medial",  word:"teacher", ja:"先生（せんせい）"},
            {sound:"CH", position:"medial",  word:"kitchen", ja:"台所（だいどころ）"},
            {sound:"CH", position:"medial",  word:"nature",  ja:"自然（しぜん）"},
            {sound:"CH", position:"final",   word:"beach",   ja:"ビーチ"},
            {sound:"CH", position:"final",   word:"catch",   ja:"つかまえる"},
            {sound:"CH", position:"final",   word:"coach",   ja:"コーチ"},
            {sound:"TS", position:"medial",  word:"outside", ja:"外側（そとがわ）"},
            {sound:"TS", position:"medial",  word:"itself",  ja:"それ自体（それじたい）"},
            {sound:"TS", position:"medial",  word:"streets", ja:"通り（とおり）"},
            {sound:"TS", position:"final",   word:"boats",   ja:"ボート（複数）"},
            {sound:"TS", position:"final",   word:"cats",    ja:"猫（ねこ）複数"},
            {sound:"TS", position:"final",   word:"roots",   ja:"根（ね）"},
            {sound:"TS", position:"final",   word:"beats",   ja:"ビート（複数）"},
            {sound:"TS", position:"final",   word:"seats",   ja:"席（せき）複数"},
            {sound:"TS", position:"final",   word:"treats",  ja:"ご褒美（ごほうび）"},
         ],
         stickers:[{emoji:"🎵",price:50},{emoji:"🎸",price:100},{emoji:"🎺",price:200},{emoji:"🎻",price:300},{emoji:"🎹",price:500}]},

    // ── LEVEL 7 ── N vs NG ─────────────────────────────────────────────────
    7: { name:"N vs NG", folder:"N_vs_NG", sounds:["N","NG"], targets:["🎋","🌿","🦆"],
         words:[
            {sound:"N", position:"initial", word:"nail",    ja:"釘（くぎ）"},
            {sound:"N", position:"initial", word:"night",   ja:"夜（よる）"},
            {sound:"N", position:"initial", word:"nose",    ja:"鼻（はな）"},
            {sound:"N", position:"medial",  word:"animal",  ja:"動物（どうぶつ）"},
            {sound:"N", position:"medial",  word:"dinner",  ja:"夕食（ゆうしょく）"},
            {sound:"N", position:"medial",  word:"money",   ja:"お金（おかね）"},
            {sound:"NG",position:"medial",  word:"anger",   ja:"怒り（いかり）"},
            {sound:"NG",position:"medial",  word:"finger",  ja:"指（ゆび）"},
            {sound:"NG",position:"medial",  word:"longer",  ja:"より長い"},
            {sound:"NG",position:"medial",  word:"single",  ja:"独身（どくしん）"},
            {sound:"N", position:"final",   word:"bone",    ja:"骨（ほね）"},
            {sound:"N", position:"final",   word:"moon",    ja:"月（つき）"},
            {sound:"N", position:"final",   word:"train",   ja:"電車（でんしゃ）"},
            {sound:"NG",position:"final",   word:"king",    ja:"王（おう）"},
            {sound:"NG",position:"final",   word:"long",    ja:"長い（ながい）"},
            {sound:"NG",position:"final",   word:"song",    ja:"歌（うた）"},
            {sound:"NG",position:"final",   word:"spring",  ja:"春（はる）"},
            {sound:"NG",position:"final",   word:"strong",  ja:"強い（つよい）"},
         ],
         stickers:[{emoji:"🌿",price:50},{emoji:"🍀",price:100},{emoji:"🌺",price:200},{emoji:"🦚",price:300},{emoji:"🌈",price:500}]},

    // ── LEVEL 8 ── V vs B ──────────────────────────────────────────────────
    8: { name:"V vs B", folder:"V_vs_B", sounds:["V","B"], targets:["🙈","🙉","🙊"],
         words:[
            {sound:"V", position:"initial", word:"van",     ja:"バン"},
            {sound:"V", position:"initial", word:"voice",   ja:"声（こえ）"},
            {sound:"V", position:"initial", word:"vote",    ja:"投票（とうひょう）"},
            {sound:"B", position:"initial", word:"ban",     ja:"禁止（きんし）"},
            {sound:"B", position:"initial", word:"bone",    ja:"骨（ほね）"},
            {sound:"B", position:"initial", word:"boat",    ja:"ボート"},
            {sound:"V", position:"medial",  word:"clever",  ja:"賢い（かしこい）"},
            {sound:"V", position:"medial",  word:"oven",    ja:"オーブン"},
            {sound:"V", position:"medial",  word:"river",   ja:"川（かわ）"},
            {sound:"B", position:"medial",  word:"table",   ja:"テーブル"},
            {sound:"B", position:"medial",  word:"number",  ja:"数（かず）"},
            {sound:"B", position:"medial",  word:"robot",   ja:"ロボット"},
            {sound:"V", position:"final",   word:"cave",    ja:"洞窟（どうくつ）"},
            {sound:"V", position:"final",   word:"live",    ja:"生きる（いきる）"},
            {sound:"V", position:"final",   word:"stove",   ja:"ストーブ"},
            {sound:"B", position:"final",   word:"web",     ja:"ウェブ"},
            {sound:"B", position:"final",   word:"robe",    ja:"ローブ"},
            {sound:"B", position:"final",   word:"tube",    ja:"チューブ"},
         ],
         stickers:[{emoji:"💧",price:50},{emoji:"🐚",price:100},{emoji:"🦀",price:200},{emoji:"🦈",price:300},{emoji:"🔱",price:500}]},

    // ── LEVEL 9 ── L vs R Blends ───────────────────────────────────────────
    9: { name:"L vs R Blends", folder:"L_blends_vs_R_blends", sounds:["L_blend","R_blend"], labels:["L","R"], targets:["🍢","🏮","👾"],
         words:[
            {sound:"L_blend_bl", position:"initial", word:"blade",  ja:"刃"},
            {sound:"L_blend_bl", position:"initial", word:"blow",   ja:"吹く"},
            {sound:"L_blend_bl", position:"initial", word:"blue",   ja:"青"},
            {sound:"L_blend_cl", position:"initial", word:"clay",   ja:"粘土"},
            {sound:"L_blend_cl", position:"initial", word:"clean",  ja:"清潔"},
            {sound:"L_blend_cl", position:"initial", word:"climb",  ja:"登る"},
            {sound:"L_blend_fl", position:"initial", word:"flag",   ja:"旗"},
            {sound:"L_blend_fl", position:"initial", word:"flat",   ja:"平ら"},
            {sound:"L_blend_fl", position:"initial", word:"flow",   ja:"流れ"},
            {sound:"L_blend_gl", position:"initial", word:"glad",   ja:"嬉しい"},
            {sound:"L_blend_gl", position:"initial", word:"glow",   ja:"輝く"},
            {sound:"L_blend_gl", position:"initial", word:"glue",   ja:"糊"},
            {sound:"L_blend_pl", position:"initial", word:"plan",   ja:"計画"},
            {sound:"L_blend_pl", position:"initial", word:"play",   ja:"遊ぶ"},
            {sound:"L_blend_pl", position:"initial", word:"plus",   ja:"プラス"},
            {sound:"R_blend_br", position:"initial", word:"brain",  ja:"脳"},
            {sound:"R_blend_br", position:"initial", word:"bread",  ja:"パン"},
            {sound:"R_blend_br", position:"initial", word:"broke",  ja:"壊れた"},
            {sound:"R_blend_cr", position:"initial", word:"crab",   ja:"カニ"},
            {sound:"R_blend_cr", position:"initial", word:"crime",  ja:"犯罪"},
            {sound:"R_blend_cr", position:"initial", word:"cross",  ja:"怒る"},
            {sound:"R_blend_fr", position:"initial", word:"frame",  ja:"枠"},
            {sound:"R_blend_fr", position:"initial", word:"free",   ja:"自由"},
            {sound:"R_blend_fr", position:"initial", word:"frog",   ja:"カエル"},
            {sound:"R_blend_gr", position:"initial", word:"grab",   ja:"つかむ"},
            {sound:"R_blend_gr", position:"initial", word:"green",  ja:"緑"},
            {sound:"R_blend_gr", position:"initial", word:"grow",   ja:"育つ"},
            {sound:"R_blend_pr", position:"initial", word:"price",  ja:"値段"},
            {sound:"R_blend_pr", position:"initial", word:"proud",  ja:"誇り高い"},
            {sound:"R_blend_pr", position:"initial", word:"prove",  ja:"証明する"},
         ],
         stickers:[{emoji:"🌊",price:50},{emoji:"🏄",price:100},{emoji:"🐬",price:200},{emoji:"🦅",price:300},{emoji:"🏆",price:500}]},
};
